services:
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"

  tools-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tools_db
    ports:
      - "5434:5432"
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    depends_on:
      - auth-db
    volumes:
      - ./auth-service:/app
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ensem.ac.ma
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - auth-db
      - tools-db
  tools-service:
    build: ./tools-service
    ports:
      - "8001:8001"
    depends_on:
      - tools-db
    volumes:
      - ./tools-service:/app
  frontend-web:
    build: ./frontend-web
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-web/src:/app/src
      - ./frontend-web/public:/app/public
    environment:
      - NEXT_PUBLIC_AUTH_API_URL=http://localhost:8000
      - NEXT_PUBLIC_TOOLS_API_URL=http://localhost:8001
    depends_on:
      - auth-service
      - tools-service